#include "globals/globals.h"

QueueHandle_t xSensorDataQueue;
QueueHandle_t xPidManagerToSysStateManagerQueue;
QueueHandle_t xSysStateManagerToPidManagerQueue;

MessageBufferHandle_t xSysStateManagerToCommsManagerMsgBuffer;
MessageBufferHandle_t xCommsManagerToSysStateManagerMsgBuffer;

