; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ESP32-S3-DevKitC-1-N8R2]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = ESP32-S3-DevKitC-1-N8R2
framework = arduino
board_build.filesystem = littlefs
debug_tool = esp-builtin
monitor_speed = 921600
monitor_filters = esp32_exception_decoder
build_flags = 
    ;-Wall -Wextra
    -Wno-deprecated-declarations
    ;-O2                         ; 
    ;-DCORE_DEBUG_LEVEL=0       ; NONE - No log output. Used to completely disable logging 
                                ;   (lowest impact on output)
    ;-DCORE_DEBUG_LEVEL=1       ; ERROR - Critical errors indicating that the software 
                                ;   cannot recover without intervention
    ;-DCORE_DEBUG_LEVEL=2       ; WARNING - Events that could potentially cause issues but 
                                ;   have been handled or mitigated
    ;-DCORE_DEBUG_LEVEL=3       ; INFO - General information messages that describe the 
                                ;   normal operation of the system
    ;-DCORE_DEBUG_LEVEL=4       ; DEBUG - Detailed diagnostic messages intended to aid in
                                ;   debugging (e.g., variable values, pointer addresses)
    -DCORE_DEBUG_LEVEL=5        ; VERBOSE - Highly detailed and frequent debugging messages,
                                ;   often including internal states, that may overwhelm the 
                                ;   output (highest impact on output)

lib_ignore =
    Micro-RTSP  ; Provides RTSP (Real-Time Streaming Protocol) server support for video streaming 
                ;   (e.g., from ESP32-CAM)
    epdiy       ; Driver for E-Paper (e-ink) displays

    Bluetooth
    BLE
    BluetoothSerial
    SimpleBLE

    WiFiProv    ; Espressif’s Wi-Fi setup helper (uses BLE/SoftAP). Part of their provisioning apps
    ESP_I2S     ; Espressif’s I2S audio interface (used for microphones, DACs, speakers)
    ESP_NOW     ; Espressif’s peer-to-peer Wi-Fi communication protocol
    ESP_SR      ; Espressif’s voice recognition library
    RainMaker   ; Espressif’s RainMaker cloud platform
    Insights    ; Espressif’s cloud diagnostics/analytics
    
    ;SPIFFS
    ;USB

    ;IoT protocols
    Matter
    OpenThread
    NetworkClientSecure 
    Zigbee

custom_component_remove =
    ;espressif/fb_gfx                    ;Some Espressif’s GFX library of some sort
    espressif/esp_modem                 ;Espressif’s ommunication with GSM/LTE modems protocols

    ;Espressif’s Zigbee IoT protocols
    espressif/esp-zboss-lib
    espressif/esp-zigbee-lib

    ;Espressif’s rainmaker cloud IoT platform protocols
    espressif/esp_rainmaker
    espressif/rmaker_common

    ;Espressif’s Wi-Fi setup helper (uses BLE/SoftAP). Part of their provisioning apps
    espressif/network_provisioning
    espressif/esp_insights              ; Espressif’s cloud diagnostics/analytics
    espressif/esp_diag_data_store
    espressif/esp_diagnostics

    espressif/cbor                      ; Espressif’s Concise Binary Object Representation
                                        ;   esentially binary data serialization
    espressif/qrcode                    ; Espressif’s QR code
    espressif/esp-sr                    ; Espressif’s voice recognition library
    espressif/libsodium                 ; Espressif’s cryptography library
    espressif/esp-modbus                ; Espressif’s modBus protocol implementation
    chmorgan/esp-libhelix-mp3           ; Espressif’s MP3 audio decoding
    espressif/esp32-camera              ; Espressif’s driver for ESP32-CAM and other cameras

lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps = 
	adafruit/Adafruit SHT31 Library@^2.2.2
	milesburton/DallasTemperature@^4.0.6
	bblanchon/ArduinoJson@7.4.3
	robtillaart/TCA9548@^0.3.1
	adafruit/Adafruit MLX90614 Library@^2.1.6
	madhephaestus/ESP32Servo@^3.2.0
	https://github.com/lily-osp/AutoTunePID
